-- Starter treatment catalog. Idempotent via ON CONFLICT (category, name).
-- Prices are indicative INR values; admins can edit them in the Treatments page.

insert into public.treatment_catalog (category, name, price, sort_order) values
  ('Consultations / X-Rays', 'Consultation & Oral Hygiene Demonstration', 690, 1),
  ('Consultations / X-Rays', 'Free Consultation', 0, 2),
  ('Consultations / X-Rays', 'Comprehensive Dental Health Check', 590, 3),
  ('Consultations / X-Rays', 'Consultation with Specialist', 990, 4),
  ('Consultations / X-Rays', 'X-Ray / IOPA - Digital', 390, 5),
  ('Consultations / X-Rays', 'OPG X-Ray - Digital', 790, 6),
  ('Restorations', 'Restoration - Anterior/Posterior (1 Surface)', 1790, 1),
  ('Restorations', 'Restoration - Nanohybrid Composite', 2490, 2),
  ('Restorations', 'Pit & Fissure Sealant', 990, 3),
  ('Restorations', 'Fluoride Application', 990, 4),
  ('Restorations', 'Desensitisation', 690, 5),
  ('Endodontics', 'RCT with Rubber Dam - using rotary', 11690, 1),
  ('Endodontics', 'Re-RCT with Rubber Dam', 12490, 2),
  ('Endodontics', 'Pulp Capping - Direct/Indirect', 3490, 3),
  ('Endodontics', 'Apicoectomy (Per tooth)', 9590, 4),
  ('Extractions', 'Extraction - Simple', 1490, 1),
  ('Extractions', 'Extraction - Non-surgical of third molar', 5790, 2),
  ('Minor Oral Surgery', 'Surgical Extraction / Impaction', 8990, 1),
  ('Minor Oral Surgery', 'Incision & Drainage', 2490, 2),
  ('Minor Oral Surgery', 'Suturing', 1490, 3),
  ('Minor Oral Surgery', 'Biopsy', 3990, 4),
  ('Crowns & Bridges', 'Crown - Metal Ceramic', 6990, 1),
  ('Crowns & Bridges', 'Crown - Zirconia', 11990, 2),
  ('Crowns & Bridges', 'Veneers', 12990, 3),
  ('Prosthodontics', 'Complete Denture (per arch)', 18990, 1),
  ('Prosthodontics', 'Removable Partial Denture', 8990, 2),
  ('Implants', 'Dental Implant (per unit)', 29990, 1),
  ('Implants', 'Bone Graft', 8990, 2),
  ('Implants', 'Membrane', 6990, 3),
  ('Periodontics', 'Scaling / Prophylaxis', 1490, 1),
  ('Periodontics', 'Curettage (per quadrant)', 2990, 2),
  ('Periodontics', 'Periodontal Flap Surgery (per quadrant)', 7990, 3),
  ('Periodontics', 'Gingivectomy', 3990, 4),
  ('Periodontics', 'Splinting', 4990, 5),
  ('Orthodontics', 'Fixed Orthodontic Treatment - Metal', 34990, 1),
  ('Orthodontics', 'Appliance & Retainers', 4990, 2),
  ('Aligners', 'Clear Aligners - Single Arch', 79990, 1),
  ('Pedodontics', 'Pedo - Pulpectomy', 3490, 1),
  ('Pedodontics', 'Pedo - Restoration', 1990, 2),
  ('Preventive', 'Preventive Care - Single', 5090, 1),
  ('Membership', 'Dental Health Plan - Premium', 2990, 1),
  ('Others', 'Bleaching / Teeth Whitening', 8990, 1),
  ('Others', 'Medication', 0, 2)
on conflict (category, name) do nothing;
